# Generated by Django 5.0.6 on 2024-10-01 10:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='اسم الحساب')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='رقم الموبايل')),
                ('allow_max', models.DecimalField(decimal_places=2, default=3000.0, max_digits=7, verbose_name='اعلى قيمة مسموح بها')),
                ('type', models.CharField(choices=[('دائن', 'دائن'), ('مدين', 'مدين')], default=('دائن', 'دائن'), max_length=16, verbose_name='نوع الحساب')),
                ('register_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ تسجيل الحساب')),
                ('active', models.BooleanField(default=True, verbose_name='حالة الحساب')),
            ],
            options={
                'verbose_name': 'الحسابات',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('سحب', 'سحب'), ('سداد', 'سداد')], default=('سحب', 'سحب'), max_length=16, verbose_name='نوع العملية')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='المبلغ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('date', models.DateField(auto_now=True, verbose_name='التاريخ')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debt_management.account')),
            ],
            options={
                'verbose_name': 'التحويلات',
            },
        ),
    ]
