# Generated by Django 5.0.6 on 2024-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_max',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=7, verbose_name='اعلى قيمة مسموح بها'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='المبلغ'),
        ),
    ]
