# Generated by Django 5.0.6 on 2024-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0002_alter_account_allow_max_alter_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('دائن', 'دائن'), ('مدين', 'مدين')], default=('دائن', 'دائن'), max_length=16, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('سحب', 'سحب'), ('إصال', 'إصال')], default=('سحب', 'سحب'), max_length=16, verbose_name='نوع العملية'),
        ),
    ]
