# Generated by Django 5.0.6 on 2024-05-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0003_alter_account_account_type_alter_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='type',
        ),
    ]
